const rawApprovedBasicCards = [
  ["001", "Luiz Inácio Lula da Silva", "L01", "Rim Dourado Clássico", "luiz-inacio-lula-da-silva"],
  ["002", "Flávio Bolsonaro", "L02", "Névoa Esmeralda", "flavio-bolsonaro"],
  ["003", "Renan Santos", "L04", "Vitral de Luz", "renan-santos"],
  ["004", "Ronaldo Caiado", "L05", "Poeira Dourada", "ronaldo-caiado"],
  ["005", "Augusto Cury", "L06", "Mármore Malaquita", "augusto-cury"],
  ["006", "Romeu Zema", "L07", "Split Ouro–Esmeralda", "romeu-zema"],
  ["007", "Pablo Marçal", "L08", "Filme 35mm", "pablo-marcal"],
  ["011", "Tarcísio de Freitas", "L09", "Reflexo Anamórfico", "tarcisio-de-freitas"],
  ["012", "Fernando Haddad", "L10", "Aurora", "fernando-haddad"],
  ["028", "Michelle Bolsonaro", "L11", "Contraluz", "michelle-bolsonaro"],
  ["031", "Gleisi Hoffmann", "L12", "Tempestade Suave", "gleisi-hoffmann"],
  ["033", "Marina Silva", "L01", "Rim Dourado Clássico", "marina-silva"],
  ["034", "Simone Tebet", "L02", "Névoa Esmeralda", "simone-tebet"],
  ["035", "Rui Costa", "L03", "Holofote Dramático", "rui-costa"],
  ["036", "Hugo Motta", "L04", "Vitral de Luz", "hugo-motta"],
  ["037", "Davi Alcolumbre", "L05", "Poeira Dourada", "davi-alcolumbre"],
  ["039", "Nikolas Ferreira", "L06", "Mármore Malaquita", "nikolas-ferreira"],
  ["042", "Bia Kicis", "L07", "Split Ouro–Esmeralda", "bia-kicis"],
  ["046", "Lindbergh Farias", "L08", "Filme 35mm", "lindbergh-farias"],
  ["048", "Guilherme Boulos", "L09", "Reflexo Anamórfico", "guilherme-boulos"],
  ["051", "Anielle Franco", "L10", "Aurora", "anielle-franco"],
  ["062", "Flávio Dino", "L11", "Contraluz", "flavio-dino"],
  ["063", "Jair Bolsonaro", "L12", "Tempestade Suave", "jair-bolsonaro"],
  ["064", "Eduardo Bolsonaro", "L01", "Rim Dourado Clássico", "eduardo-bolsonaro"],
  ["065", "Carlos Bolsonaro", "L02", "Névoa Esmeralda", "carlos-bolsonaro"],
  ["072", "Rodrigo Pacheco", "L03", "Holofote Dramático", "rodrigo-pacheco"],
  ["073", "Rogério Marinho", "L04", "Vitral de Luz", "rogerio-marinho"],
  ["079", "Kim Kataguiri", "L05", "Poeira Dourada", "kim-kataguiri"],
  ["080", "André Janones", "L06", "Mármore Malaquita", "andre-janones"],
  ["083", "Carla Zambelli", "L07", "Split Ouro–Esmeralda", "carla-zambelli"],
  ["084", "Tabata Amaral", "L08", "Filme 35mm", "tabata-amaral"],
  ["085", "Glauber Braga", "L09", "Reflexo Anamórfico", "glauber-braga"],
  ["086", "Sérgio Moro", "L10", "Aurora", "sergio-moro"],
  ["095", "Deltan Dallagnol", "L11", "Contraluz", "deltan-dallagnol"],
  ["098", "Ricardo Nunes", "L12", "Tempestade Suave", "ricardo-nunes"],
];

export const approvedBasicCards = rawApprovedBasicCards.map(([personId, person, look, lookName, slug]) => ({
  personId,
  person,
  look,
  lookName,
  image: `/chromas/approved/${personId}_${slug}.jpg`,
  aiEdited: true,
  edition: "basic",
}));

export const preservedChromaAlternatives = [
  {
    personId: "002",
    person: "Flávio Bolsonaro",
    sourceId: "002b",
    look: "L03",
    lookName: "Holofote Dramático",
    status: "preserved-outside-app",
  },
];
