export const TOPIC_IDS = {
  POLITICS: "politica-em-jogo",
  JUSTICE: "justica-escandalos",
  SIDES: "direita-esquerda",
  RACE_2026: "corrida-2026",
  TRENDING: "em-alta",
};

export const TOPICS = [
  {
    id: TOPIC_IDS.POLITICS,
    label: "Política em Jogo",
    icon: "🏛️",
    description: "O catálogo completo da vida pública brasileira.",
  },
  {
    id: TOPIC_IDS.JUSTICE,
    label: "Justiça & Escândalos",
    icon: "⚖️",
    description: "Tribunais, investigações e personagens de casos nacionais.",
  },
  {
    id: TOPIC_IDS.SIDES,
    label: "Direita x Esquerda",
    icon: "↔️",
    description: "No duelo principal, cada confronto coloca um nome de direita contra um de esquerda.",
  },
  {
    id: TOPIC_IDS.RACE_2026,
    label: "Corrida 2026",
    icon: "🗳️",
    description: "As chapas presidenciais que estão no jogo eleitoral.",
  },
  {
    id: TOPIC_IDS.TRENDING,
    label: "Em Alta",
    icon: "🔥",
    description: "Os nomes mais presentes no debate político do momento.",
  },
];

const JUSTICE_NAMES = new Set([
  "Alexandre de Moraes",
  "Alessandro Antônio Stefanutto",
  "Almir Garnier Santos",
  "Anderson Torres",
  "André Mendonça",
  "Andrei Rodrigues",
  "Anthony Garotinho",
  "Antonio Carlos Ferreira",
  "Antônio Carlos Camilo Antunes (Careca do INSS)",
  "Antônio Carlos Freixo Júnior (Mineiro)",
  "Antônio Carlos Welter",
  "Athayde Ribeiro Costa",
  "Augusto Heleno",
  "Braga Netto",
  "Carla Zambelli",
  "Carlos Eduardo Thompson Flores Lenz",
  "Carlos Fernando dos Santos Lima",
  "Cármen Lúcia",
  "Carolina Lebbos",
  "Celso de Mello",
  "Cristiano Zanin",
  "Daniel Vorcaro",
  "Deltan Dallagnol",
  "Dias Toffoli",
  "Diogo Castor de Mattos",
  "Edson Fachin",
  "Eduardo Bolsonaro",
  "Eduardo Cunha",
  "Erika Marena",
  "Fabiano Zettel",
  "Fábio Augusto Vieira",
  "Fernando Collor de Mello",
  "Gabriela Hardt",
  "Gilmar Mendes",
  "Henrique Vorcaro",
  "Isabel Cristina Groba Vieira",
  "Jair Messias Bolsonaro",
  "Januário Paludo",
  "Jerusa Burmann Viecili",
  "João Pedro Gebran Neto",
  "Joaquim Barbosa",
  "Jorge Messias",
  "José Roberto Arruda",
  "Júlio Cesar de Arruda",
  "Laura Gonçalves Tessler",
  "Leandro Almada da Costa",
  "Leandro Paulsen",
  "Luis Felipe Salomão",
  "Luís Roberto Barroso",
  "Luiz Fux",
  "Luiz Inácio Lula da Silva",
  "Luiz Philippe Vieira de Mello Filho",
  "Marco Aurélio Mello",
  "Marco Edson Gonçalves Dias (G. Dias)",
  "Mário Fernandes",
  "Maurício Camisotti",
  "Maurício Valeixo",
  "Mauro Cid",
  "Nelson Tanure",
  "Nunes Marques",
  "Orlando Martello Júnior",
  "Paulo Gonet",
  "Paulo Sérgio Nogueira de Oliveira",
  "Raquel Dodge",
  "Ricardo Lewandowski",
  "Ricardo Villas Bôas Cueva",
  "Roberson Pozzetti",
  "Rodrigo Janot",
  "Rogério Galloro",
  "Sergio Moro",
  "Valdemar Costa Neto",
  "Victor Luiz dos Santos Laus",
  "Viviane Barci de Moraes",
  "Wellington César Lima e Silva",
]);

const RIGHT_NAMES = new Set([
  "Adriana Ventura",
  "Alexandre Garcia",
  "Alfredo Gaspar",
  "Almir Garnier Santos",
  "Anderson Torres",
  "André Fernandes",
  "André Valadão",
  "Augusto Heleno",
  "Augusto Nunes",
  "Bia Kicis",
  "Braga Netto",
  "Cabo Daciolo",
  "Caio Coppolla",
  "Carla Zambelli",
  "Carlos Bolsonaro",
  "Clariana Barão",
  "Cleitinho Azevedo",
  "Damares Alves",
  "Eduardo Bolsonaro",
  "Eduardo Girão",
  "Eduardo Pazuello",
  "Edir Macedo",
  "Flávio Bolsonaro",
  "Gustavo Gayer",
  "Gusttavo Lima",
  "Hamilton Mourão",
  "Hélio Lopes",
  "Jair Messias Bolsonaro",
  "Kim Kataguiri",
  "Leonardo Avalanche",
  "Lucas Pavanato",
  "Luciano Hang",
  "Magno Malta",
  "Marcel van Hattem",
  "Marco Feliciano",
  "Marcos Pontes",
  "Marina Helena",
  "Mário Frias",
  "Maurício Souza",
  "Michelle Bolsonaro",
  "Nando Moura",
  "Neymar Jr.",
  "Nikolas Ferreira",
  "Pablo Marçal",
  "Pastor Gil",
  "Paulo Figueiredo",
  "Paulo Guedes",
  "Renan Santos",
  "Ricardo Salles",
  "Robson Rodovalho",
  "Rodrigo Constantino",
  "Rogério Marinho",
  "Romeu Zema",
  "Ronaldo Caiado",
  "Rosângela Moro",
  "Sargento Fahur",
  "Sergio Moro",
  "Sikêra Júnior",
  "Silas Malafaia",
  "Sóstenes Cavalcante",
  "Tarcísio de Freitas",
  "Tereza Cristina",
  "Valdemar Costa Neto",
  "Valdemiro Santiago",
  "Vitor Belfort",
  "Wilson Grassi",
]);

const LEFT_NAMES = new Set([
  "Alessandro Molon",
  "Alexandre Padilha",
  "Anielle Franco",
  "Anitta",
  "Caetano Veloso",
  "Camilo Santana",
  "Chico Alencar",
  "Chico Buarque",
  "Dilma Rousseff",
  "Duda Salabert",
  "Edinho Silva",
  "Edmilson Costa",
  "Elmano de Freitas",
  "Erika Hilton",
  "Fátima Bezerra",
  "Felipe Neto",
  "Fernando Haddad",
  "Fábio Luís Lula da Silva (Lulinha)",
  "Gilberto Gil",
  "Gleisi Hoffmann",
  "Guilherme Boulos",
  "Hertz Dias",
  "Humberto Costa",
  "Ian Neves",
  "Ivan Valente",
  "Janja da Silva",
  "Jaques Wagner",
  "Jean Wyllys",
  "Jerônimo Rodrigues",
  "João Pedro Stédile",
  "Jones Manoel",
  "José Guimarães",
  "Leonardo Pericles",
  "Luiz Inácio Lula da Silva",
  "Luiz Marinho",
  "Luiza Erundina",
  "Macaé Evaristo",
  "Márcia Lopes",
  "Marcelo Freixo",
  "Maria do Rosário",
  "Marina Silva",
  "Miriam Belchior",
  "Orlando Silva",
  "Paulo Paim",
  "Paulo Teixeira",
  "Randolfe Rodrigues",
  "Rui Costa",
  "Rui Costa Pimenta",
  "Sabrina Fernandes",
  "Samara Martins",
  "Sâmia Bomfim",
  "Sidônio Palmeira",
  "Sofia Manzano",
  "Sônia Guajajara",
  "Talíria Petrone",
  "Teresa Leitão",
  "Vera Lúcia",
  "Wagner Moura",
  "Walter Casagrande",
  "Wellington Dias",
]);

const TRENDING_NAMES = new Set([
  "Alexandre de Moraes",
  "Alexandre Padilha",
  "Alessandro Antônio Stefanutto",
  "Anderson Torres",
  "André Mendonça",
  "Antônio Carlos Camilo Antunes (Careca do INSS)",
  "Arthur Lira",
  "Augusto Cury",
  "Braga Netto",
  "Caio Coppolla",
  "Camilo Santana",
  "Carla Zambelli",
  "Carlos Bolsonaro",
  "Ciro Gomes",
  "Ciro Nogueira",
  "Clariana Barão",
  "Cristiano Zanin",
  "Daniel Vorcaro",
  "Damares Alves",
  "Davi Alcolumbre",
  "Edmilson Costa",
  "Eduardo Bolsonaro",
  "Erika Hilton",
  "Felipe Neto",
  "Fernando Haddad",
  "Flávio Bolsonaro",
  "Flávio Dino",
  "Geraldo Alckmin",
  "Gilberto Kassab",
  "Gilmar Mendes",
  "Gleisi Hoffmann",
  "Guilherme Boulos",
  "Gusttavo Lima",
  "Hertz Dias",
  "Hugo Motta",
  "Jair Messias Bolsonaro",
  "Janja da Silva",
  "Jorge Messias",
  "Luciano Huck",
  "Luiz Inácio Lula da Silva",
  "Marina Silva",
  "Maurício Camisotti",
  "Mauro Cid",
  "Michelle Bolsonaro",
  "Neymar Jr.",
  "Nikolas Ferreira",
  "Pablo Marçal",
  "Paulo Gonet",
  "Renan Santos",
  "Rogério Marinho",
  "Romeu Zema",
  "Ronaldo Caiado",
  "Rui Costa",
  "Rui Costa Pimenta",
  "Samara Martins",
  "Sidônio Palmeira",
  "Silas Malafaia",
  "Simone Tebet",
  "Tarcísio de Freitas",
  "Tereza Cristina",
  "Valdemar Costa Neto",
  "Wilson Grassi",
]);

export function topicById(topicId) {
  return TOPICS.find((topic) => topic.id === topicId) || TOPICS[0];
}

export function politicalSideFor(candidate) {
  if (RIGHT_NAMES.has(candidate?.name)) return "direita";
  if (LEFT_NAMES.has(candidate?.name)) return "esquerda";
  return null;
}

export function topicIdsForCandidate(candidate) {
  const topicIds = [TOPIC_IDS.POLITICS];
  if (JUSTICE_NAMES.has(candidate?.name)) topicIds.push(TOPIC_IDS.JUSTICE);
  if (politicalSideFor(candidate)) topicIds.push(TOPIC_IDS.SIDES);
  if (candidate?.corrida2026 === true) topicIds.push(TOPIC_IDS.RACE_2026);
  if (TRENDING_NAMES.has(candidate?.name)) topicIds.push(TOPIC_IDS.TRENDING);
  return topicIds;
}

export function decorateCandidate(candidate) {
  return {
    ...candidate,
    topics: topicIdsForCandidate(candidate),
    politicalSide: politicalSideFor(candidate),
  };
}

export function candidatesForTopic(candidates, topicId) {
  const selected = topicById(topicId).id;
  return candidates.filter((candidate) => topicIdsForCandidate(candidate).includes(selected));
}

export function pairAllowedForTopic(topicId, byId) {
  if (topicId !== TOPIC_IDS.SIDES) return () => true;
  return (leftId, rightId) => {
    const leftSide = politicalSideFor(byId[leftId]);
    const rightSide = politicalSideFor(byId[rightId]);
    return Boolean(leftSide && rightSide && leftSide !== rightSide);
  };
}
